### PR TITLE
test: add test checking transformation when types are wrapped as generic

### PR DESCRIPTION
**Pull request by misino**

### CODE REVIEW

**Comment by misino** [comment]
Hmmm...but this test is failing. I struggle with how to make proper type conversion.

**Comment by havardh** [comment]
Ah, I didn't see the issue you created and just saw the test and a passing CI test. Sorry about that. I will look at it when I have some time. :)

**Comment by havardh** [comment]
I continue the discussion on the issue.

**Comment by havardh** [comment]
Resolves #48

**Pull request merged**
